---
- name: Apply/update policies
  uri:
    url: "{{ central_url }}/v1/authProviders"
    body: "{{ lookup('template', 'templates/auth0/auth_config.json.j2' ) }}"
    method: POST
    user: admin
    password: "{{ admin_password }}"
    body_format: json
    force_basic_auth: true
    validate_certs: no
  register: authProvider

- debug: var=authProvider

- name: Create Auth0 group
  uri:
    url: "{{ central_url }}/v1/groups"
    body: "{{ lookup('template', 'templates/auth0/group.json.j2' ) }}"
    method: POST
    user: admin
    password: "{{ admin_password }}"
    body_format: json
    force_basic_auth: true
    validate_certs: no  
